export { USER_QUERY, POST_QUERY, GREATOFPOST_QUERY, GREATOFUSER_QUERY, MULTIPOST_QUERY, IMAGE_QUERY} from './queries'
export { ADD_USER, ADD_POST, DELETE_POST, UPDATE_POST, UPDATE_GREAT, UPLOAD_IMAGE } from './mutations'
export {} from './subscriptions'
